Fix attribute options rules issue
flagbit/akeneo-table-attribute-bundle pull request #65
Opened 2021-09-21 14:13 UTC by flagbird

Fixes #62

2021-09-23 11:56 UTC, amansilla commented on src/Controller/AjaxOptionController.php
> +    private $baseController;
Why not defining type?

2021-09-23 12:25 UTC, amansilla requested changes
- Code can be improved. Waiting for @flagbird's feedback. 

- Locally tested code works as intended ✅

2021-09-23 12:26 UTC, amansilla commented
@pascal-zarrad FYI: This PR should be tested using Akeneo EE, since rules are only in EE included.

2021-09-23 14:28 UTC, flagbird commented on src/Controller/AjaxOptionController.php
> +    private $baseController;
Good point. 7.4 is the only version that is supported in Akeneo 5 and since it's new code it won't break BC.

2021-09-23 14:29 UTC, amansilla commented on src/Controller/AjaxOptionController.php
> +    private $baseController;
Yeah, I tested as well changing it, and letting it run doesn't look to break anything.

2021-09-23 14:42 UTC, flagbird commented
master should have been rebased into this branch. The button on GitHub PR pages to update a branch does only merge. :-/

2021-09-23 14:52 UTC, amansilla commented
> master should have been rebased into this branch. The button on GitHub PR pages to update a branch does only merge. :-/

Yeah not nice for the git history maybe we can check if we can change that on repo configuration.

2021-09-23 14:53 UTC, amansilla approved these changes

2021-09-28 14:19 UTC, Vogaeael approved these changes
Looks good to me

2021-09-28 14:21 UTC, merged