Add Akeneo 6 support
flagbit/akeneo-table-attribute-bundle pull request #75
Opened 2022-10-10 10:26 UTC by elias-knodel

## Description

This Pull Request adds support for the newest Akeneo 6 version.

## Related issue

Resolves #73 
Resolves #74 

## How can this be tested?

- Installation on an Akeneo v6 instance should work without issues.
- Automatic tests should pass

2022-10-25 13:47 UTC, mralexandernickel requested changes

2022-10-25 13:47 UTC, mralexandernickel commented on .scrutinizer.yml
> +          version: "8.0.*"
```suggestion
          version: "8.0"
```

2022-10-27 09:04 UTC, flagbird requested changes
Please also update Code-Sniffer. Their php constraint doesn't look promising.

2022-10-27 10:13 UTC, flagbird commented
Scrutinizer seems to use its own composer file. It can be handled with the Scrutinizer config: https://scrutinizer-ci.com/docs/tools/php/code-sniffer/

2022-10-27 13:02 UTC, flagbird approved these changes

2022-10-28 11:52 UTC, mralexandernickel approved these changes

2022-10-28 12:14 UTC, merged